name: Week 01 PyTest Suite

on:
  push:
    paths:
      - 'tests/practice_week_01/**'
  pull_request:
    paths:
      - 'tests/practice_week_01/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run tests
      run: pytest tests/practice_week_01 --maxfail=2 --disable-warnings -q